
steps:
  build:
    image: alpine
    commands:
      - apk add --update --no-cache $SCHEME make git openssh-client
      - make benchmark
      - find dist/benchmarks -type f -exec echo {} \; -exec cat {} \;
      - sh scripts/update-benchmarks-git-branch.sh
    when:
      branch: [master]
    secrets: [ REPOLOGKEY ]

matrix:
  SCHEME:
    - guile
