
steps:
  build:
    image: alpine
    commands:
      - apk add --update --no-cache $SCHEME make git openssh-client
      - sh scripts/compile-benchmarks.sh
      - make benchmark
      - find dist/benchmarks -type f -exec echo {} \; -exec cat {} \;
      - sh scripts/update-benchmarks-git-branch.sh
    secrets: [ REPOLOGKEY ]
    when:
      - event: push
        branch: [master]

matrix:
  SCHEME:
    - guile guile-dev
