
steps:
  build:
    image: alpine
    commands:
      - apk add --no-cache $SCHEME make git
      - make build
      - CI=0 make test
    when:
      - event: push
        branch: [master]

matrix:
  SCHEME:
    - guile
