
name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scheme: [guile-3.0]

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y ${{ matrix.scheme }}
    - name: Run build
      run: make build
    - name: Run test
      run: make test
    - name: Run benchmarks
      run: make benchmark
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: benchmarks
        path: |
          dist/benchmarks
